### PR TITLE
[ FEATURE ] - Add Atlantis Pipeline 

### PR DESCRIPTION
**Pull request by leandromoreirati**
Add atlantis pipeline to infrasturcture deployment.

### CODE REVIEW

**Comment by thiago-scherrer** [comment]
atlantis plan -w dev -d deployment/terraform

**Comment by unicobot-engprod** [comment]
Ran Plan for dir: `deployment/terraform` workspace: `dev`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -upgrade -reconfigure" in "/atlantis/repos/acesso-io/techcore-cvat/198/dev/deployment/terraform": exit status 1
Upgrading modules...
Downloading git::ssh://git@github.com/acesso-io/terraform-gcp-cloud-sql.git?ref=v1.0.2 for cvat_postgresql...
- cvat_postgresql in .terraform/modules/cvat_postgresql
Downloading git::ssh://git@github.com/acesso-io/terraform-null-label.git?ref=1.1.0 for postgresql_label...
- postgresql_label in .terraform/modules/postgresql_label
Downloading git::ssh://git@github.com/acesso-io/terraform-gcp-memorystore.git?ref=1.3.0 for redis...
- redis in .terraform/modules/redis
Downloading git::ssh://git@github.com/acesso-io/terraform-gcp-secret-manager.git?ref=1.1.0 for redis_cvat_secret...
- redis_cvat_secret in .terraform/modules/redis_cvat_secret
Downloading git::ssh://git@github.com/acesso-io/terraform-null-label.git?ref=1.1.0 for redis_label...
- redis_label in .terraform/modules/redis_label
Downloading git::ssh://git@github.com/acesso-io/terraform-null-label.git?ref=1.1.0 for secret_redis_label...
- secret_redis_label in .terraform/modules/secret_redis_label
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid default value for variable
│ 
│   on variables.tf line 39, in variable "context":
│   39:   default = {
│   40:     dev = {
│   41:       environment  = "dev"
│   42:       project      = "acesso-core-dev"
│   43:       project_host = "acesso-host-dev"
│   44:       region       = "us-east1"
│   45:       zone         = "us-east1-b"
│   46:       private_network = "projects/acesso-host-dev/global/networks/acesso-dev-vpc"
│   47:       network         = "acesso-core-dev-us-ea1-subnet"
│   48:       subnetwork      = "acesso-core-dev-us-ea1-subnet"
│   49:       pgsql_engine                  = "POSTGRES_13"
│   50:       pgsql_machine_type            = "db-f1-micro"
│   51:       pgsql_disk_size               = "10"
│   52:       pgsql_disk_autoresize         = true
│   53:       pgsql_disk_type               = "PD_SSD"
│   54:       pgsql_master_zone             = "us-east1-b"
│   55:       pgsql_enable_failover_replica = false
│   56:       pgsql_num_read_replicas       = 0
│   57:       pgsql_read_replica_zones      = []
│   58:       pgsql_maintenance_window_day  = 6
│   59:       pgsql_maintenance_window_hour = 2
│   60:       pgsql_backup_enabled          = true
│   61:       pgsql_backup_start_time       = "04:00"
│   62:       pgsql_maintenance_track       = "stable"
│   63:       redis_version             = "REDIS_6_X"
│   64:       redis_auth_enabled        = "true"
│   65:       redis_memory_size_gb      = "16"
│   66:       redis_tier                = "BASIC"
│   67:       redis_location_id         = "us-east1-b"
│   68:       redis_connect_mode        = "PRIVATE_SERVICE_ACCESS"
│   69:       redis_maintenance_day     = "SUNDAY"
│   70:       redis_maintenance_hours   = "23"
│   71:       redis_maintenance_minutes = "30"
│   72:       redis_maintenance_seconds = "0"
│   73:       redis_maintenance_nanos   = "0"
│   74:     }
│   75:     prod = {
│   76:       environment  = "prod"
│   77:       project      = "acesso-core-prod"
│   78:       project_host = "acesso-host-prod"
│   79:       region       = "us-east1"
│   80:       zone         = "us-east1-b"
│   81:       private_network = "projects/acesso-host-prod/global/networks/acesso-prod-vpc"
│   82:       network         = "acesso-core-prod-us-ea1-subnet"
│   83:       subnetwork      = "acesso-core-prod-us-ea1-subnet"
│   84:       pgsql_engine                  = "POSTGRES_13"
│   85:       pgsql_machine_type            = "db-f1-micro"
│   86:       pgsql_disk_size               = "10"
│   87:       pgsql_disk_autoresize         = true
│   88:       pgsql_disk_type               = "PD_SSD"
│   89:       pgsql_master_zone             = "us-east1-b"
│   90:       pgsql_enable_failover_replica = true
│   91:       pgsql_num_read_replicas       = 0
│   92:       pgsql_read_replica_zones      = []
│   93:       pgsql_maintenance_window_day  = 6
│   94:       pgsql_maintenance_window_hour = 2
│   95:       pgsql_backup_enabled          = true
│   96:       pgsql_backup_start_time       = "04:00"
│   97:       pgsql_maintenance_track       = "stable"
│   98:       redis_version                 = "REDIS_6_X"
│   99:       redis_auth_enabled            = "true"
│  100:       redis_memory_size_gb          = "16"
│  101:       redis_tier                    = "BASIC"
│  102:       redis_location_id             = "us-east1-b"
│  103:       redis_alternative_location_id = "us-east1-c"
│  104:       redis_connect_mode            = "PRIVATE_SERVICE_ACCESS"
│  105:       redis_maintenance_day         = "SUNDAY"
│  106:       redis_maintenance_hours       = "23"
│  107:       redis_maintenance_minutes     = "30"
│  108:       redis_maintenance_seconds     = "0"
│  109:       redis_maintenance_nanos       = "0"
│  110:     }
│  111:   }
│ 
│ This default value is not compatible with the variable's type constraint:
│ all map elements must have the same type.
╵


```
</details>

**Comment by thiago-scherrer** [comment]
WIP

**Comment by thiago-scherrer** [comment]
WIP

**Comment by thiago-scherrer** [comment]
Remove tf data

**Pull request closed without merging**
